[package]
name = "twelve-days-of-xmas"
version = "0.1.0"
authors = ["Chibin Zhang <benjaminzhang1130@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
